//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAVAR_JHB_DBEntities : DbContext
    {
        public BAVAR_JHB_DBEntities()
            : base("name=BAVAR_JHB_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAboutUs> tblAboutUs { get; set; }
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblAppVersion> tblAppVersion { get; set; }
        public virtual DbSet<tblCar> tblCar { get; set; }
        public virtual DbSet<tblCarProduct> tblCarProduct { get; set; }
        public virtual DbSet<tblCity> tblCity { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblGift> tblGift { get; set; }
        public virtual DbSet<tblGiftSendWay> tblGiftSendWay { get; set; }
        public virtual DbSet<tblHonors_Lincenses> tblHonors_Lincenses { get; set; }
        public virtual DbSet<tblLog> tblLog { get; set; }
        public virtual DbSet<tblNotification> tblNotification { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblOrderDetail> tblOrderDetail { get; set; }
        public virtual DbSet<tblOrderState> tblOrderState { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblProductImage> tblProductImage { get; set; }
        public virtual DbSet<tblProductProperty> tblProductProperty { get; set; }
        public virtual DbSet<tblProductsSerial> tblProductsSerial { get; set; }
        public virtual DbSet<tblProductSuggestion> tblProductSuggestion { get; set; }
        public virtual DbSet<tblProperty> tblProperty { get; set; }
        public virtual DbSet<tblRelativeProduct> tblRelativeProduct { get; set; }
        public virtual DbSet<tblSerialInputLog> tblSerialInputLog { get; set; }
        public virtual DbSet<tblService> tblService { get; set; }
        public virtual DbSet<tblSlideShow> tblSlideShow { get; set; }
        public virtual DbSet<tblSmsLog> tblSmsLog { get; set; }
        public virtual DbSet<tblSuggestion> tblSuggestion { get; set; }
        public virtual DbSet<tblSuggestionState> tblSuggestionState { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserCar> tblUserCar { get; set; }
        public virtual DbSet<tblUserGift> tblUserGift { get; set; }
        public virtual DbSet<tblUserGiftState> tblUserGiftState { get; set; }
        public virtual DbSet<tblUserRegisterProduct> tblUserRegisterProduct { get; set; }
        public virtual DbSet<tblUserType> tblUserType { get; set; }
    }
}
