//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuggestion
    {
        public long Id { get; set; }
        public Nullable<long> IdUser { get; set; }
        public string Title { get; set; }
        public string QuestionText { get; set; }
        public Nullable<System.DateTime> DateQuestionText { get; set; }
        public string AnswerText { get; set; }
        public Nullable<System.DateTime> DateAnswerText { get; set; }
        public string Unit { get; set; }
        public Nullable<int> IdState { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<long> IdUser_Insert { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public Nullable<long> IdUser_Update { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<long> IdUser_Delete { get; set; }
        public Nullable<bool> StateDelete { get; set; }
    
        public virtual tblSuggestionState tblSuggestionState { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
