//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGift
    {
        public long Id { get; set; }
        public Nullable<long> IdGift { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<int> MinPoint { get; set; }
        public Nullable<long> IdGiftSendWay { get; set; }
        public Nullable<long> IdAgent_User { get; set; }
        public Nullable<int> IdUserGiftState { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<long> IdUser_Insert { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public Nullable<long> IdUser_Update { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<long> IdUser_Delete { get; set; }
        public Nullable<bool> StateDelete { get; set; }
    
        public virtual tblGift tblGift { get; set; }
        public virtual tblGiftSendWay tblGiftSendWay { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUserGiftState tblUserGiftState { get; set; }
    }
}
