//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblOrder = new HashSet<tblOrder>();
            this.tblSuggestion = new HashSet<tblSuggestion>();
            this.tblUserCar = new HashSet<tblUserCar>();
            this.tblUserGift = new HashSet<tblUserGift>();
            this.tblUserRegisterProduct = new HashSet<tblUserRegisterProduct>();
        }
    
        public long Id { get; set; }
        public string CodeMelli { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<long> IdCity { get; set; }
        public string Mobile { get; set; }
        public string Tell { get; set; }
        public Nullable<System.DateTime> DateBirthday { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<bool> Married { get; set; }
        public string JobName { get; set; }
        public Nullable<bool> Home { get; set; }
        public Nullable<long> IdUserType { get; set; }
        public Nullable<int> StateRegister { get; set; }
        public string Address { get; set; }
        public string AccountCode { get; set; }
        public string CodePostal { get; set; }
        public string Fathername { get; set; }
        public string LatLon { get; set; }
        public string AgentCode { get; set; }
        public Nullable<double> AgentRate { get; set; }
        public string AgentLicenseImage { get; set; }
        public string Agent_History { get; set; }
        public string Agent_Place_Area { get; set; }
        public string Agent_BankAcouuntNumber { get; set; }
        public Nullable<bool> Agent_Lisence { get; set; }
        public Nullable<bool> Agent_JobType { get; set; }
        public Nullable<bool> Agent_Malek { get; set; }
        public Nullable<bool> Agent_PosState { get; set; }
        public Nullable<int> Agent_IdType { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<long> IdUser_Insert { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public Nullable<long> IdUser_Update { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<long> IdUser_Delete { get; set; }
        public Nullable<bool> StateDelete { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestion> tblSuggestion { get; set; }
        public virtual tblUserType tblUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserCar> tblUserCar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserGift> tblUserGift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserRegisterProduct> tblUserRegisterProduct { get; set; }
    }
}
